version: "3.8"

services:

  janus:
    image: janus-gateway
    build:
      context: .
      dockerfile: Dockerfile.janus
    network_mode: host

  nginx:
    image: nginx
    volumes:
      - ./configs/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/cert.pem:/etc/certs/cert.pem
      - ./certs/key.pem:/etc/certs/key.pem
    network_mode: service:janus
