version: "3.8"

services:

  janus:
    image: janus-gateway
    build:
      context: .
      dockerfile: Dockerfile.janus
    network_mode: host
    volumes:
      - ./janus:/opt/templates
    env_file: .env

  nginx:
    image: nginx
    volumes:
      - ./configs/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - /opt/certs:/etc/certs
    network_mode: service:janus
